[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
murkfi = "G41tUc85R5a8DbrHSsjcLUTNqDEULKZrU9kPDN3waWSv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/anon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
