[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
murk_vault_manager = "3VNZYCSkJk1UwJMQVRrS2y14oxxwKKC3hajoWsXpvHEQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node app/*.ts"
